// MOCK DATA — reemplazar en Fase 2 por datos reales desde el backend.
import type { Cliente } from "./types";

export const clientes: Cliente[] = [
  {
    codigo: "CLI-0001",
    nombre: "Abastos La Esperanza",
    tipo: "Tienda",
    direccion: "Av. Bolívar Norte, C.C. La Esperanza",
    ciudad: "Valencia",
    lat: 10.1751,
    lng: -68.0011,
    telefono: "+58 241 555 0101",
    email: "compras@laesperanza.com",
  },
  {
    codigo: "CLI-0002",
    nombre: "Distribuidora Don Pepe",
    tipo: "Distribuidor",
    direccion: "Calle Real, Sector Los Ruices",
    ciudad: "Caracas",
    lat: 10.4956,
    lng: -66.8836,
    telefono: "+58 212 555 0102",
    email: "pedidos@donpepe.com",
  },
  {
    codigo: "CLI-0003",
    nombre: "Supermercado Frescos",
    tipo: "Tienda",
    direccion: "Av. Las Delicias, C.C. Frescos Plaza",
    ciudad: "Maracay",
    lat: 10.2569,
    lng: -67.5859,
    telefono: "+58 243 555 0103",
    email: "compras@frescosmercado.com",
  },
  {
    codigo: "CLI-0004",
    nombre: "Heladería Polo Norte",
    tipo: "Tienda",
    direccion: "Av. Francisco de Miranda, Chacao",
    ciudad: "Caracas",
    lat: 10.4966,
    lng: -66.8536,
    telefono: "+58 212 555 0104",
    email: "gerencia@polonorte.com",
  },
  {
    codigo: "CLI-0005",
    nombre: "Mayorista Los Andes",
    tipo: "Distribuidor",
    direccion: "Av. Libertador, Zona Este",
    ciudad: "Barquisimeto",
    lat: 10.0747,
    lng: -69.347,
    telefono: "+58 251 555 0105",
    email: "ventas@mayoristalosandes.com",
  },
  {
    codigo: "CLI-0006",
    nombre: "Pizzería Roma Express",
    tipo: "Tienda",
    direccion: "Av. Bolívar, C.C. Roma",
    ciudad: "Valencia",
    lat: 10.1685,
    lng: -68.0125,
    telefono: "+58 241 555 0106",
    email: "pedidos@romaexpress.com",
  },
  {
    codigo: "CLI-0007",
    nombre: "Abasto El Trigal",
    tipo: "Tienda",
    direccion: "Sector El Trigal Centro",
    ciudad: "Valencia",
    lat: 10.1462,
    lng: -68.0198,
    telefono: "+58 241 555 0107",
    email: "compras@eltrigal.com",
  },
  {
    codigo: "CLI-0008",
    nombre: "Distribuidora Oriente",
    tipo: "Distribuidor",
    direccion: "Av. Rómulo Gallegos, Sector Oriente",
    ciudad: "Caracas",
    lat: 10.4886,
    lng: -66.8236,
    telefono: "+58 212 555 0108",
    email: "administracion@distoriente.com",
  },
];
