// MOCK DATA — reemplazar en Fase 2 por datos reales desde el backend.
import type { Despacho, DespachoAprobacion } from "./types";

export const despachos: Despacho[] = [
  {
    id: "desp-1",
    numero: "D-0001",
    ventaId: "venta-1",
    origenId: "alm-catia",
    destinoClienteId: "CLI-0002",
    creadoPorId: "usr-3",
    estado: "PENDIENTE_APROBACION",
    fechaCreacion: "2026-08-05",
    fechaEstimadaEntrega: null,
    vehiculoId: null,
    distanciaEstimadaKm: null,
    tiempoEstimadoMin: null,
    rutaCalculada: false,
    items: [
      { id: "di-1", productoId: "prod-11", cantidad: 20 },
      { id: "di-2", productoId: "prod-4", cantidad: 30 },
    ],
  },
  {
    id: "desp-2",
    numero: "D-0002",
    ventaId: "venta-3",
    origenId: "alm-catia",
    destinoClienteId: "CLI-0001",
    creadoPorId: "usr-3",
    estado: "ENTREGADO",
    fechaCreacion: "2026-07-31",
    fechaEstimadaEntrega: "2026-08-01",
    vehiculoId: "veh-1",
    distanciaEstimadaKm: 165,
    tiempoEstimadoMin: 150,
    rutaCalculada: true,
    items: [
      { id: "di-3", productoId: "prod-6", cantidad: 20 },
      { id: "di-4", productoId: "prod-14", cantidad: 10 },
    ],
  },
  {
    id: "desp-3",
    numero: "D-0003",
    ventaId: null,
    origenId: "alm-catia",
    destinoClienteId: "CLI-0004",
    creadoPorId: "usr-3",
    estado: "BORRADOR",
    fechaCreacion: "2026-08-07",
    fechaEstimadaEntrega: null,
    vehiculoId: null,
    distanciaEstimadaKm: null,
    tiempoEstimadoMin: null,
    rutaCalculada: false,
    items: [
      { id: "di-5", productoId: "prod-5", cantidad: 15 },
      { id: "di-6", productoId: "prod-8", cantidad: 30 },
    ],
  },
  {
    id: "desp-4",
    numero: "D-0004",
    ventaId: null,
    origenId: "alm-catia",
    destinoClienteId: "CLI-0003",
    creadoPorId: "usr-3",
    estado: "APROBADO",
    fechaCreacion: "2026-08-03",
    fechaEstimadaEntrega: null,
    vehiculoId: null,
    distanciaEstimadaKm: null,
    tiempoEstimadoMin: null,
    rutaCalculada: false,
    items: [
      { id: "di-7", productoId: "prod-11", cantidad: 15 },
      { id: "di-8", productoId: "prod-16", cantidad: 25 },
    ],
  },
  {
    id: "desp-5",
    numero: "D-0005",
    ventaId: null,
    origenId: "alm-catia",
    destinoClienteId: "CLI-0002",
    creadoPorId: "usr-3",
    estado: "RECHAZADO",
    fechaCreacion: "2026-08-02",
    fechaEstimadaEntrega: null,
    vehiculoId: null,
    distanciaEstimadaKm: null,
    tiempoEstimadoMin: null,
    rutaCalculada: false,
    items: [{ id: "di-9", productoId: "prod-1", cantidad: 200 }],
  },
  {
    id: "desp-6",
    numero: "D-0006",
    ventaId: null,
    origenId: "alm-catia",
    destinoClienteId: "CLI-0008",
    creadoPorId: "usr-3",
    estado: "EN_PREPARACION",
    fechaCreacion: "2026-08-06",
    fechaEstimadaEntrega: null,
    vehiculoId: "veh-2",
    distanciaEstimadaKm: null,
    tiempoEstimadoMin: null,
    rutaCalculada: false,
    items: [
      { id: "di-10", productoId: "prod-18", cantidad: 30 },
      { id: "di-11", productoId: "prod-13", cantidad: 20 },
    ],
  },
  {
    id: "desp-7",
    numero: "D-0007",
    ventaId: null,
    origenId: "alm-catia",
    destinoClienteId: "CLI-0005",
    creadoPorId: "usr-3",
    estado: "EN_TRANSITO",
    fechaCreacion: "2026-08-05",
    fechaEstimadaEntrega: "2026-08-07",
    vehiculoId: "veh-1",
    distanciaEstimadaKm: 355,
    tiempoEstimadoMin: 260,
    rutaCalculada: true,
    items: [
      { id: "di-12", productoId: "prod-2", cantidad: 300 },
      { id: "di-13", productoId: "prod-9", cantidad: 60 },
    ],
  },
  {
    id: "desp-8",
    numero: "D-0008",
    ventaId: null,
    origenId: "alm-catia",
    destinoClienteId: "CLI-0008",
    creadoPorId: "usr-3",
    estado: "CANCELADO",
    fechaCreacion: "2026-07-25",
    fechaEstimadaEntrega: null,
    vehiculoId: null,
    distanciaEstimadaKm: null,
    tiempoEstimadoMin: null,
    rutaCalculada: false,
    items: [{ id: "di-14", productoId: "prod-15", cantidad: 10 }],
  },
];

export const despachoAprobaciones: DespachoAprobacion[] = [
  {
    id: "dap-1",
    despachoId: "desp-2",
    usuarioId: "usr-4",
    accion: "APROBADA",
    comentario: "Cliente al día tras la revisión de venta; se aprueba el despacho.",
    fecha: "2026-07-31",
  },
  {
    id: "dap-2",
    despachoId: "desp-4",
    usuarioId: "usr-4",
    accion: "APROBADA",
    comentario: null,
    fecha: "2026-08-03",
  },
  {
    id: "dap-3",
    despachoId: "desp-5",
    usuarioId: "usr-4",
    accion: "RECHAZADA",
    comentario: "Faltan datos del vehículo asignado y el destino no está confirmado; se rechaza el despacho.",
    fecha: "2026-08-02",
  },
  {
    id: "dap-4",
    despachoId: "desp-6",
    usuarioId: "usr-4",
    accion: "APROBADA",
    comentario: null,
    fecha: "2026-08-06",
  },
  {
    id: "dap-5",
    despachoId: "desp-7",
    usuarioId: "usr-4",
    accion: "APROBADA",
    comentario: null,
    fecha: "2026-08-04",
  },
];
