// MOCK DATA — reemplazar en Fase 2 por datos reales desde el backend.
// Toda la flota tiene su base en el unico almacen de la empresa (Almacén Catia).
import type { Vehiculo } from "./types";

export const vehiculos: Vehiculo[] = [
  {
    id: "veh-1",
    placa: "AB123CD",
    tipo: "CAMION_REFRIGERADO",
    capacidadKg: 3000,
    tieneRefrigeracion: true,
    estado: "FUNCIONAL",
    almacenBaseId: "alm-catia",
    conductorNombre: "Andrea Silva",
    ultimaRevision: "2026-07-20",
  },
  {
    id: "veh-2",
    placa: "AC456DE",
    tipo: "CAMION_REFRIGERADO",
    capacidadKg: 3000,
    tieneRefrigeracion: true,
    estado: "FUNCIONAL",
    almacenBaseId: "alm-catia",
    conductorNombre: "Freddy González",
    ultimaRevision: "2026-07-15",
  },
  {
    id: "veh-3",
    placa: "AD789FG",
    tipo: "CAMIONETA",
    capacidadKg: 1200,
    tieneRefrigeracion: true,
    estado: "EN_MANTENIMIENTO",
    almacenBaseId: "alm-catia",
    conductorNombre: "Luis Bravo",
    ultimaRevision: "2026-08-02",
  },
  {
    id: "veh-4",
    placa: "AE012HI",
    tipo: "CAMIONETA",
    capacidadKg: 1200,
    tieneRefrigeracion: true,
    estado: "FUNCIONAL",
    almacenBaseId: "alm-catia",
    conductorNombre: "Kelly Marín",
    ultimaRevision: "2026-06-28",
  },
  {
    id: "veh-5",
    placa: "AF345JK",
    tipo: "MOTO",
    capacidadKg: 50,
    tieneRefrigeracion: false,
    estado: "FUNCIONAL",
    almacenBaseId: "alm-catia",
    conductorNombre: "Ronald Peña",
    ultimaRevision: "2026-07-10",
  },
  {
    id: "veh-6",
    placa: "AG678LM",
    tipo: "CAMION_REFRIGERADO",
    capacidadKg: 3000,
    tieneRefrigeracion: true,
    estado: "FUERA_DE_SERVICIO",
    almacenBaseId: "alm-catia",
    conductorNombre: null,
    ultimaRevision: "2026-05-05",
  },
  {
    id: "veh-7",
    placa: "AH901NO",
    tipo: "CAMION_REFRIGERADO",
    capacidadKg: 2500,
    tieneRefrigeracion: true,
    estado: "FUNCIONAL",
    almacenBaseId: "alm-catia",
    conductorNombre: "Carlos Uzcátegui",
    ultimaRevision: "2026-07-29",
  },
  {
    id: "veh-8",
    placa: "AI234PQ",
    tipo: "CAMIONETA",
    capacidadKg: 1000,
    tieneRefrigeracion: false,
    estado: "FUNCIONAL",
    almacenBaseId: "alm-catia",
    conductorNombre: "Marisela Gómez",
    ultimaRevision: "2026-07-18",
  },
];
